### ISSUE TITLE
Лицензия

### ISSUE THREAD

**Issue by Xottab-DUTY** [OGSR/Configurator#1]
Стоит добавить лицензию, в которой указано, каким образом можно использовать эти исходники.
Благо, лицензий очень много: от разлицензии (UNLICENCE) до "не трогай и не используй, только смотри".

**Comment by KRodinn** [comment]
Зачем? Этот репо не настолько важный чтоб тут чего-то лицензировать, тем более что изначально этот конфигуратор создавал KD с кем-то, а не я.
Я вообще этот репо заархивировать хотел, что скорее всего и сделаю в скором времени.
